### ISSUE TITLE
Fails with ansible-2.10

### ISSUE THREAD

**Issue by Justin-Randall** [ripclawffb/ansible-collection-helix-core#24] opened 2021-05-14 16:49 UTC
It seems many modules are broken with 2.10.

After using ansible galaxy to install, the following error appears:

```
ERROR! couldn't resolve module/action 'ripclawffb.helix_core_depot'. This often indicates a misspelling, missing collection, or incorrect module path.

The error appears to be in '/XXX/p4d-ansible/roles/helix-p4-depots/tasks/main.yml': line 4, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:


- name: Ensure Depot Exists
  ^ here

```

**Comment by ripclawffb** [comment] 2021-05-14 22:03
What is the output when you type `ansible-galaxy collection list`?

For example, on my machine I see:
```
Collection            Version
--------------------- -------
ripclawffb.helix_core 1.0.3
```

**Comment by ripclawffb** [comment] 2021-05-15 03:43
I just tested with Ansible 2.10.9 and it seems to work. Here's what my environment looks like:

Playbook:
```
- hosts: localhost
  tasks:
    - name: Create a new depot
      ripclawffb.helix_core.helix_core_depot:
        state: present
        depot: bruno
        type: local
        description: Bruno's depot
        map: depot/...
        p4port: '1666'
        p4user: ''
        p4passwd: ''
```
Ansible Version:
```
$ ansible-playbook --version
ansible-playbook 2.10.9
  config file = /root/ansible-control-repo/ansible.cfg
  configured module search path = ['/root/.ansible/plugins/modules', '/usr/share/ansible/plugins/modules']
  ansible python module location = /root/.local/share/virtualenvs/ansible-control-repo-Ns4rt0gI/lib/python3.8/site-packages/ansible
  executable location = /root/.local/share/virtualenvs/ansible-control-repo-Ns4rt0gI/bin/ansible-playbook
  python version = 3.8.3 (default, May 28 2020, 21:46:02) [GCC 8.3.1 20190507 (Red Hat 8.3.1-4)]
```

Playbook Run:
```
$ ansible-playbook playbooks/profiles/profile-perforcemaster.yml 

PLAY [localhost] *************************************************************************************************************************************

TASK [Gathering Facts] *******************************************************************************************************************************
ok: [localhost]

TASK [Create a new depot] ****************************************************************************************************************************
ok: [localhost]

PLAY RECAP *******************************************************************************************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0 
```

Result:
```
$ p4 depot -o bruno
# A Perforce Depot Specification.
#
#  Depot:       The name of the depot.
#  Owner:       The user who created this depot.
#  Date:        The date this specification was last modified.
#  Description: A short description of the depot (optional).
#  Type:        Whether the depot is 'local', 'remote',
#               'stream', 'spec', 'archive', 'tangent',
#               'unload', 'extension' or 'graph'.
#               Default is 'local'.
#  Address:     Connection address (remote depots only).
#  Suffix:      Suffix for all saved specs (spec depot only).
#  StreamDepth: Depth for streams in this depot (stream depots only).
#  Map:         Path translation information (must have ... in it).
#  SpecMap:     For spec depot, which specs should be recorded (optional).
#
# Use 'p4 help depot' to see more about depot forms.

Depot:  bruno

Owner:  root

Date:   2021/05/14 20:31:09

Description:
        Bruno's depot

Type:   local

Map:    depot/...
```

**Comment by ripclawffb** [comment] 2021-06-03 03:24
I'm closing this issue for now since I wasn't able to reproduce the issue.

**Closed by ripclawffb** 2021-06-03 03:24 UTC
